# Generated by Django 4.1.2 on 2022-10-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fname',
            field=models.CharField(default='name', max_length=15),
            preserve_default=False,
        ),
    ]
